### ISSUE TITLE
Can you help me now ? I am asking for help now unofficial 

### ISSUE THREAD

**Issue by Saikatsaha1996** [agnostic-apollo/tudo#1]
I want to set path in my bashrc
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/system/vendor/lib64:/system/vendor/lib64/egl
But it is not possible.. so how can I set.. actually i can't understand properly because to complicated..
And i am not professional..

Thank you advance!..
Tudo already installed..

**Comment by Saikatsaha1996** [comment]
@agnostic-apollo  r you available for help 🥲

**Comment by agnostic-apollo** [comment]
Why do you want to do that? Termux uses `DT_RUNPATH` instead of `LD_LIBRARY_PATH` by default and may break. Just run binaries like `tudo <some-binary>` and it will automatically set `LD_LIBRARY_PATH` appropriately.

**Comment by agnostic-apollo** [comment]
You have a typo in `$LD_LIBRARY_PATH`, you are using `echo "$LD_LIBARY_PATH"`. And `gcc` is not provided by termux and it provides `clang` instead. And issue could be related to mixing of android and prefix libs or `gcc` itself. The one from pointless repo is very old and likely broken since not compatible with newer version of termux libs. You could try https://github.com/Maxython/glibc-for-termux

**Comment by Saikatsaha1996** [comment]
> You have a typo in `$LD_LIBRARY_PATH`, you are using `echo "$LD_LIBARY_PATH"`. And `gcc` is not provided by termux and it provides `clang` instead. And issue could be related to mixing of android and prefix libs or `gcc` itself. The one from pointless repo is very old and likely broken since not compatible with newer version of termux libs. You could try https://github.com/Maxython/glibc-for-termux

Happy New year
And thank you for your reply

**Comment by agnostic-apollo** [comment]
You too. Welcome.
